### ISSUE TITLE
TCM sampler in sd-diffusion-webui

### ISSUE THREAD

**Issue by George0726** [jabir-zheng/TCD#4]
Thanks for the impressive work. It would be great if supporting the sampler in SD-diffusion-webui

**Comment by jabir-zheng** [comment]
Thank you for your interest in our work. We're considering the proposal for SD-WebUI support, but the exact timeline for implementation is still uncertain.

**Comment by bigmover** [comment]
> Thank you for your interest in our work. We're considering the proposal for SD-WebUI support, but the exact timeline for implementation is still uncertain.

Hi @jabir-zheng  Any plan to add an official SD WebUI support?
