### ISSUE TITLE
Any plans for SD 1.5 LoRA?

### ISSUE THREAD

**Issue by burgalon** [jabir-zheng/TCD#5]
Thank you for publishing this. This result is quite awesome and it's great to see how the details can get such X10 improvements!

**Comment by jabir-zheng** [comment]
Thank you for recognizing our work!

As requested, we are currently training TCD-LoRA for SD1.5 and its variant. We will release the checkpoint as soon as the sanity checks are completed.

**Comment by Tolga077** [comment]
Thanks in advance, I'll wait for the 1.5 checkpoint.
