### ISSUE TITLE
implementation in ComfyUI framework

### ISSUE THREAD

**Issue by dfl** [jabir-zheng/TCD#7]
Thank for your excellent contribution!

I am attempting to implement this for the ComfyUI community, however there are some differences in structure between Diffusers (more explicit time scheduling) and ComfyUI (array of sigmas, and abstracted scheduling).

The tricky part is how to do the adjusted timestep calculation using eta/gamma.
Something is incorrect so the image just goes black after the first step, when eta is > 0.

I wonder someone on your team would be able to look at my code please? (or anyone else here on GitHub who is good with diffusers and comfyui)
https://github.com/dfl/comfyui-tcd-scheduler

**Comment by jabir-zheng** [comment]
Thank you sincerely for your tremendous efforts!

My team and I will attempt to address this during our available time. However, as we are not well-versed in ComfyUI, this process might take some time. 

Assistance from individuals experienced with ComfyUI would be greatly appreciated!

**Comment by wandrzej** [comment]
![image](https://github.com/jabir-zheng/TCD/assets/26924000/42465d01-555a-4918-a6bc-f17083891ab3)
top batch of 4 - sdxl checkpoint with 16 steps
middle - same checkpoint with 4 steps
bottom, same checkpoint with 4 steps and this LoRA applied. 
So looks like even without special implementation this gives far more crisp results on it's own, through the vanilla Load LoRA node.

**Comment by mhh0318** [comment]
> ![image](https://private-user-images.githubusercontent.com/26924000/312448655-42465d01-555a-4918-a6bc-f17083891ab3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMzk5ODEsIm5iZiI6MTcxMDMzOTY4MSwicGF0aCI6Ii8yNjkyNDAwMC8zMTI0NDg2NTUtNDI0NjVkMDEtNTU1YS00OTE4LWE2YmMtZjE3MDgzODkxYWIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDE0MjEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiZDJkOGU1MjdmMjBjYmFlZmIwNzA4ZTVjMTNlNDNhYzMzMzUyMDE4YjFkOTllZTFlMzIyZmQ4MjY4MmU5NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aKq99EKxKpHM8Aay1FV6osC0oyWK1pdeLuvyW-iwMUs) top batch of 4 - sdxl checkpoint with 16 steps middle - same checkpoint with 4 steps bottom, same checkpoint with 4 steps and this LoRA applied. So looks like even without special implementation this gives far more crisp results on it's own, through the vanilla Load LoRA node.

Yup. It shares the same scheduler with LCM when gamma=0. When using other samplers, you could also find an alignment.  Could you provide which type of sampler used for the bottom batch?

**Comment by wandrzej** [comment]
> Yup. It shares the same scheduler with LCM when gamma=0. When using other samplers, you could also find an alignment. Could you provide which type of sampler used for the bottom batch?

99% sure it was DPM++ SDE, with CFG ~2, as those were the settings I was using with a lightning version of a checkpoint. Unlike the Lightning LoRA which requires euler + sgm scheduler, the DPM++ SDE seems to be the consensus preferred option. I tried it without much hope of it working, and it just did. Most likely not the right way of doing it, nor optimal, but the effect is clear. 

I'll later re-run the experiment to confirm.

**Comment by MoonRide303** [comment]
@jabir-zheng Correct me if I am wrong, but it looks like your method requires your custom scheduler to work as intended. In ComfyUI code base best place to add new custom scheduler would be probably [comfy_extras/nodes_custom_sampler.py](https://github.com/comfyanonymous/ComfyUI/blob/master/comfy_extras/nodes_custom_sampler.py). You can take look at existing schedulers implementation as a reference, and then propose a PR to ComfyUI repo.

**Comment by dfl** [comment]
@jabir-zheng please see my comments here... can you assist in my understanding? https://github.com/dfl/comfyui-tcd-scheduler/issues/1#issuecomment-2009312833

**Comment by dfl** [comment]
I have created a ddpm branch in my repo, but I need some help with injecting the gamma-modified sigma  https://github.com/dfl/comfyui-tcd-scheduler/tree/ddpm

**Comment by mhh0318** [comment]
Please check this awesome implementation. https://github.com/jabir-zheng/TCD/issues/16 by @JettHu

**Comment by bigmover** [comment]
> Please check this awesome implementation. #16 by @JettHu

Does this implementation lack a schedule or I missed something?
